name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

env:
  QUICALC_LOG: error,quicalc=debug
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check

  check-features:
    name: Check with --no-default-features ${{ matrix.feat_debug }} ${{ matrix.feat_python }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        feat_debug: ["", "-F debug"]
        feat_python: ["", "-F python"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --no-default-features ${{ matrix.feat_debug }} ${{ matrix.feat_python }}

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy -- -D warnings

  clippy-features:
    name: Clippy with --no-default-features ${{ matrix.feat_debug }} ${{ matrix.feat_python }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        feat_debug: ["", "-F debug"]
        feat_python: ["", "-F python"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy --no-default-features ${{ matrix.feat_debug }} ${{ matrix.feat_python }} -- -D warnings
